PatitasLove3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patitasLove.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patitasLove/urls.py
from django.urls import path
# from . import views 
from .views import home, contacto, registro, agregar_al_carrito, ver_carrito, agregar_producto, listar_producto, editar_producto, eliminar_producto, crear_venta, pago_exitoso, listar_ventas, descargar_ventas_excel

urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('registro/', registro, name="registro"),
    path('agregar/<int:producto_id>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/',ver_carrito, name='ver_carrito'),
    path('agregar_producto/', agregar_producto, name='agregar_producto'),
    path('listar_producto/', listar_producto, name='listar_producto'),
    path('editar_producto/<int:id>/', editar_producto, name='editar_producto'),
    path('eliminar_producto/<int:id>/', eliminar_producto, name='eliminar_producto'),
    path('crear_venta/', crear_venta, name='crear_venta'),    
    path('pago_exitoso/', pago_exitoso, name='pago_exitoso'),
    path('listar_ventas/', listar_ventas, name='listar_ventas'),
    path('descargar_ventas_excel/', descargar_ventas_excel, name='descargar_ventas_excel'),
]

patitasLove/models.py
from django.db import models

# Create your models here.
class Producto(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    marca = models.CharField(max_length=100)
    precio = models.IntegerField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return f"{self.nombre} ({self.marca}) - ${self.precio}"
    
class Carrito(models.Model):
    id = models.AutoField(primary_key=True)
    productos = models.ManyToManyField(Producto, through='CarritoItem')

class CarritoItem(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.producto.precio * self.cantidad

    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre}"
    
# class Venta(models.Model):
#     id = models.AutoField(primary_key=True)
#     fecha = models.DateTimeField(auto_now_add=True)
#     productos = models.ManyToManyField(Producto, through='VentaProducto')

class Venta(models.Model):
    id = models.AutoField(primary_key=True)
    fecha = models.DateTimeField(auto_now_add=True)
    productos = models.ManyToManyField(Producto, through='VentaProducto')

    def total(self):
        total = sum(item.producto.precio * item.cantidad for item in self.ventaproducto_set.all())
        return total
    
class VentaProducto(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

patitasLove/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    precio = forms.IntegerField(widget=forms.TextInput(attrs={
        'class': 'appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-pink-500 focus:border-pink-500 focus:z-10 sm:text-sm',
        'min': 0,    # Valor mínimo permitido
        'inputmode': 'numeric',  # Indicar que se espera un valor numérico
    }))

    class Meta:
        model = Producto
        fields = ['nombre', 'marca', 'precio', 'imagen']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-pink-500 focus:border-pink-500 focus:z-10 sm:text-sm'}),
            'marca': forms.TextInput(attrs={'class': 'appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-pink-500 focus:border-pink-500 focus:z-10 sm:text-sm'}),
            # 'imagen': forms.ClearableFileInput(attrs={'class': 'appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-pink-500 focus:border-pink-500 focus:z-10 sm:text-sm'}),
        }

patitasLove/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from .models import Producto, Carrito, CarritoItem, Venta, VentaProducto
from .forms import ProductoForm
# from django.core import serializers
from django.db.models import Q
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from django.template.loader import render_to_string
import io
import csv
from datetime import datetime
import pytz
from .models import Venta, VentaProducto
import xlsxwriter


# Create your views here.


def home(request):
    productos = Producto.objects.all()
    data = {
        'productos': productos
    }
    # se saco esto en el return , data
    return render(request, 'patitasLove/home.html', data)

def contacto(request):
    return render(request, 'patitasLove/contacto.html')

def registro(request):
    return render(request, 'patitasLove/registro.html')

def agregar_al_carrito(request, producto_id):
   
    producto = get_object_or_404(Producto, id=producto_id)
    carrito_id = request.session.get('carrito_id')

    if carrito_id:
        carrito = Carrito.objects.get(id=carrito_id)
    else:
        carrito = Carrito.objects.create()
        request.session['carrito_id'] = carrito.id

    item, created = CarritoItem.objects.get_or_create(carrito=carrito, producto=producto)
    if not created:
        item.cantidad += 1
        item.save()

 
    return redirect('ver_carrito')

def ver_carrito(request):
    carrito_id = request.session.get('carrito_id')
    if carrito_id:
        carrito = Carrito.objects.get(id=carrito_id)
        items = CarritoItem.objects.filter(carrito=carrito)
        total = sum(item.subtotal() for item in items)
    else:
        carrito = None
        items = []
        total = 0
    data = {
        'items': items,
        'total': total,
    }
    return render(request, 'patitasLove/carrito.html', data)

# def eliminar_del_carrito(request, producto_id):
#     carrito_id = request.session.get('carrito_id')
#     carrito = get_object_or_404(Carrito, id=carrito_id)
#     producto = get_object_or_404(Producto, id=producto_id)
#     item = CarritoItem.objects.get(carrito=carrito, producto=producto)
#     item.delete()

#     return redirect('ver_carrito')

def agregar_producto(request):
    data = {
        'form': ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "Guardado Correctamente"
        else:
            data["form"] = formulario

    return render(request, 'patitasLove/producto/agregar.html', data)

def listar_producto(request):
    productos = Producto.objects.all()

    data = {
        'productos': productos
    }
    return render(request, 'patitasLove/producto/listar.html', data)

def editar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)

    data = {
        'form': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            # data["mensaje"] = "Editado Correctamente"
            return redirect(to='listar_producto')
        data["form"] = formulario
    return render(request,'patitasLove/producto/modificar.html', data)

def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    return redirect(to='listar_producto')

# def crear_venta(request):
#     venta = Venta.objects.create()
#     carrito_id = request.session.get('carrito_id')
#     if request.method == 'POST':
#         data = CarritoItem.objects.all()
#         carrito_items_json = serializers.serialize('json', data)
#         carrito_items = json.loads(carrito_items_json)  # Convertir cadena JSON a lista de diccionarios
        
#         carrito_items_filtrados = [item for item in carrito_items if item['fields']['carrito'] == carrito_id]

#         for carrito_item in carrito_items_filtrados:
#             producto = Producto.objects.get(id=carrito_item['fields']['producto'])
#             item, created = VentaProducto.objects.get_or_create(venta=venta, producto=producto)
            
#             if carrito_item['fields']['cantidad'] > 1:
#                 item.cantidad = carrito_item['fields']['cantidad']
#                 item.save()

#     return redirect(to='pago_exitoso')

def crear_venta(request):
    carrito_id = request.session.get('carrito_id')
    if not carrito_id:
        # Si no hay carrito, redirigir a la página de carrito
        return redirect('ver_carrito')

    carrito = get_object_or_404(Carrito, id=carrito_id)
    items = CarritoItem.objects.filter(carrito=carrito)

    if not items.exists():
        # Si no hay ítems en el carrito, redirigir a la página de carrito
        return redirect('ver_carrito')

    venta = Venta.objects.create()

    for item in items:
        VentaProducto.objects.create(venta=venta, producto=item.producto, cantidad=item.cantidad)
    
    # Eliminar todos los ítems del carrito
    items.delete()

    # Limpiar el carrito de la sesión
    del request.session['carrito_id']

    return redirect('pago_exitoso')

def pago_exitoso(request):
    return render(request, 'patitasLove/pago_exitoso.html')

def listar_ventas(request):
    # Obtener las ventas
    ventas = Venta.objects.all()

    # Obtener los parámetros de fecha desde y hasta de la solicitud GET
    fecha_desde_str = request.GET.get('fecha_desde')
    fecha_hasta_str = request.GET.get('fecha_hasta')

    # Convertir las cadenas de fecha a objetos datetime si existen
    if fecha_desde_str and fecha_hasta_str:
        fecha_desde = datetime.strptime(fecha_desde_str, '%Y-%m-%d').date()
        fecha_hasta = datetime.strptime(fecha_hasta_str, '%Y-%m-%d').date()

        # Filtrar las ventas por fecha usando Q objects para combinar condiciones OR
        ventas = ventas.filter(
            Q(fecha__date__gte=fecha_desde) &
            Q(fecha__date__lte=fecha_hasta)
        )

    # Contexto para pasar a la plantilla
    data = {
        'ventas': ventas
    }

    return render(request, 'patitasLove/ventas/listar_ventas.html', data)


def descargar_ventas_excel(request):
    # Obtener parámetros de fecha desde la solicitud GET
    fecha_desde_str = request.GET.get('fecha_desde')
    fecha_hasta_str = request.GET.get('fecha_hasta')

    # Convertir las cadenas de fecha a objetos datetime si existen
    if fecha_desde_str and fecha_hasta_str:
        fecha_desde = datetime.strptime(fecha_desde_str, '%Y-%m-%d').date()
        fecha_hasta = datetime.strptime(fecha_hasta_str, '%Y-%m-%d').date()

        # Filtrar ventas por fecha usando Q objects para combinar condiciones OR
        ventas = Venta.objects.filter(
            fecha__date__gte=fecha_desde,
            fecha__date__lte=fecha_hasta
        )
    else:
        # Si no se proporcionan fechas, descargar todas las ventas
        ventas = Venta.objects.all()

    # Crear el libro de trabajo y la hoja de cálculo en blanco
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename="ventas.xlsx"'

    workbook = xlsxwriter.Workbook(response)
    worksheet = workbook.add_worksheet('Ventas')

    # Encabezados de columna
    headers = ['ID Venta', 'Fecha', 'Producto', 'Cantidad', 'Valor Unitario', 'Subtotal']
    for col, header in enumerate(headers):
        worksheet.write(0, col, header)

    # Escribir datos de ventas
    row = 1
    for venta in ventas:
        productos_venta = VentaProducto.objects.filter(venta=venta)

        for producto_venta in productos_venta:
            producto = producto_venta.producto
            cantidad = producto_venta.cantidad
            valor_unitario = producto.precio
            subtotal = cantidad * valor_unitario

            # Escribir datos en la hoja de cálculo
            worksheet.write(row, 0, venta.id)
            worksheet.write(row, 1, venta.fecha.strftime('%d/%m/%Y'))
            worksheet.write(row, 2, f"{producto.nombre} ({cantidad} x ${valor_unitario})")
            worksheet.write(row, 3, cantidad)
            worksheet.write(row, 4, valor_unitario)
            worksheet.write(row, 5, subtotal)
            row += 1

    workbook.close()
    return response

patitasLove/templates/patitasLove/producto/agregar.html
{% extends 'patitasLove/base.html' %}
{% load static %}
{% block contenido %}
<div class="container mx-auto px-4 mt-24 mb-24 ">
    <div class="max-w-lg mx-auto">
        <h2 class="text-2xl font-semibold mb-4">Agregar Producto</h2>
        <form class="space-y-6" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
                <div class="mb-4">
                    <label for="id_nombre" class="block text-gray-700 mb-2">Nombre:</label>
                    {{ form.nombre }}
                </div>
                <div class="mb-4">
                    <label for="id_marca" class="block text-gray-700 mb-2">Marca:</label>
                    {{ form.marca }}
                </div>
                <div class="mb-4">
                    <label for="id_precio" class="block text-gray-700 mb-2">Precio:</label>
                    {{ form.precio }}
                </div>
                <div class="mb-6">
                    <label for="id_imagen" class="block text-gray-700 mb-2">Imagen:</label>
                    {{ form.imagen }}
                </div>
            </div>
            <div class="flex justify-between">
                <button type="submit" value="Guardar"
                    class="group relative w-1/2 flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-pink-600 hover:bg-pink-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500 mr-2">
                    Guardar Producto
                </button>
                <a href="{% url 'home' %}"
                    class="group relative w-1/2 flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 ml-2">
                    Cancelar
                </a>
            </div>

        </form>
        <div class="mt-6">
            {% if mensaje %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <strong class="font-bold">¡Éxito!</strong>
                <span class="block sm:inline">{{ mensaje }}</span>
            </div>
            {% endif %}
            <!-- {% if form.errors %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <strong class="font-bold">¡Error!</strong>
                <span class="block sm:inline">Por favor corrija los errores en el formulario.</span>
            </div>
            {% endif %} -->
        </div>
    </div>
</div>

{% endblock %}

patitasLove/templates/patitasLove/producto/listar.html
{% extends 'patitasLove/base.html' %}
{% load static %}
{% load humanize %}
{% block contenido %}
<div class="container mx-auto px-4 mt-24 mb-24">
    <div class="w-full">
        <h2 class="text-2xl font-semibold mb-4">Lista de Productos</h2>
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <!-- <div class="px-4 py-5 sm:px-6">
                <h3 class="text-lg leading-6 font-medium text-gray-900">Todos los Productos</h3>
            </div> -->
            <div class="border-t border-gray-200">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Nombre
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Marca
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Precio
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Imagen
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% for producto in productos %}
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-900">{{ producto.nombre }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-900">{{ producto.marca }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-900">${{ producto.precio | intcomma }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}"
                                        class="h-12 w-12 rounded-full">
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <a href="{% url 'editar_producto' producto.id %}"
                                        class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-3 rounded">
                                        Editar
                                    </a>
                                    <a href="{% url 'eliminar_producto' producto.id %}"
                                        class="inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-3 rounded">
                                        Editar
                                    </a>
                                </td>
                                
                                
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

patitasLove/templates/patitasLove/producto/modificar.html
{% extends 'patitasLove/base.html' %}
{% load static %}
{% block contenido %}
<div class="container mx-auto px-4 mt-24 mb-24 ">
    <div class="max-w-lg mx-auto">
        <h2 class="text-2xl font-semibold mb-4">Editar Producto</h2>
        <form class="space-y-6" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
                <div class="mb-4">
                    <label for="id_nombre" class="block text-gray-700 mb-2">Nombre:</label>
                    {{ form.nombre }}
                </div>
                <div class="mb-4">
                    <label for="id_marca" class="block text-gray-700 mb-2">Marca:</label>
                    {{ form.marca }}
                </div>
                <div class="mb-4">
                    <label for="id_precio" class="block text-gray-700 mb-2">Precio:</label>
                    {{ form.precio }}
                </div>
                <div class="mb-6">
                    <label for="id_imagen" class="block text-gray-700 mb-2">Imagen:</label>
                    {{ form.imagen }}
                </div>
            </div>
            <div class="flex justify-between">
                <button type="submit" value="Editar"
                    class="group relative w-1/2 flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-pink-600 hover:bg-pink-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500 mr-2">
                    Guardar Producto
                </button>
                <a href="{% url 'home' %}"
                    class="group relative w-1/2 flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 ml-2">
                    Cancelar
                </a>
            </div>

        </form>
        <div class="mt-6">
            {% if mensaje %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <strong class="font-bold">¡Éxito!</strong>
                <span class="block sm:inline">{{ mensaje }}</span>
            </div>
            {% endif %}
            <!-- {% if form.errors %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <strong class="font-bold">¡Error!</strong>
                <span class="block sm:inline">Por favor corrija los errores en el formulario.</span>
            </div>
            {% endif %} -->
        </div>
    </div>
</div>

{% endblock %}